#!/usr/bin/env bash
# Fix Apache to serve Hello Holberton by creating the index and starting the service

echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
echo "apache2 is running"
