#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

sed -i '/listen 80 default_server;/a \	add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
