#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
apt-get update -y
apt-get install -y haproxy
cat > /etc/haproxy/haproxy.cfg <<EOF
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend localnodes
	bind *:80
	mode http
	default_backend nodes

backend nodes
	mode http
	balance roundrobin
	option forwardfor
	server web-01 52.70.87.10:80 check
	server web-02 3.93.218.74:80 check
EOF
service haproxy restart
