#!/usr/bin/env bash
# Install Nginx and serve Holberton School at /

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
chmod 644 /var/www/html/index.html

service nginx start