#!/usr/bin/env bash
# Install nginx and configure it to serve Holberton School

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart