#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing "Ceci n'est pas une page" and /redirect_me

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Default index
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Add redirect rule and 404 page inside server block
sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.wilsonn.vercel.app;\n\t}\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart